//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5477
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStockService
{
    
    string GetData(int value);
    
    CompositeType GetDataUsingDataContract(CompositeType composite);
    
    bool AuthenticateUser(string userName, string password);
    
    StockItem GetStockItem(string code);
    
    CostPlace[] GetCostPlaces();
    
    void Book(string itemNr, decimal quanity);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetData", Namespace="http://tempuri.org/")]
public partial class GetDataRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int value;
    
    public GetDataRequest()
    {
    }
    
    public GetDataRequest(int value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataResponse", Namespace="http://tempuri.org/")]
public partial class GetDataResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string GetDataResult;
    
    public GetDataResponse()
    {
    }
    
    public GetDataResponse(string GetDataResult)
    {
        this.GetDataResult = GetDataResult;
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/StockService")]
public partial class CompositeType
{
    
    private bool boolValueField;
    
    private bool boolValueFieldSpecified;
    
    private string stringValueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool BoolValue
    {
        get
        {
            return this.boolValueField;
        }
        set
        {
            this.boolValueField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BoolValueSpecified
    {
        get
        {
            return this.boolValueFieldSpecified;
        }
        set
        {
            this.boolValueFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string StringValue
    {
        get
        {
            return this.stringValueField;
        }
        set
        {
            this.stringValueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/StockService")]
public partial class CostPlace
{
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/StockService")]
public partial class StockItem
{
    
    private string descriptionField;
    
    private string no_Field;
    
    private System.Nullable<decimal> stockQuantityField;
    
    private bool stockQuantityFieldSpecified;
    
    private string uOMField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string No_
    {
        get
        {
            return this.no_Field;
        }
        set
        {
            this.no_Field = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public System.Nullable<decimal> StockQuantity
    {
        get
        {
            return this.stockQuantityField;
        }
        set
        {
            this.stockQuantityField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StockQuantitySpecified
    {
        get
        {
            return this.stockQuantityFieldSpecified;
        }
        set
        {
            this.stockQuantityFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string UOM
    {
        get
        {
            return this.uOMField;
        }
        set
        {
            this.uOMField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataUsingDataContract", Namespace="http://tempuri.org/")]
public partial class GetDataUsingDataContractRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public CompositeType composite;
    
    public GetDataUsingDataContractRequest()
    {
    }
    
    public GetDataUsingDataContractRequest(CompositeType composite)
    {
        this.composite = composite;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDataUsingDataContractResponse", Namespace="http://tempuri.org/")]
public partial class GetDataUsingDataContractResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public CompositeType GetDataUsingDataContractResult;
    
    public GetDataUsingDataContractResponse()
    {
    }
    
    public GetDataUsingDataContractResponse(CompositeType GetDataUsingDataContractResult)
    {
        this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="AuthenticateUser", Namespace="http://tempuri.org/")]
public partial class AuthenticateUserRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string userName;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    public AuthenticateUserRequest()
    {
    }
    
    public AuthenticateUserRequest(string userName, string password)
    {
        this.userName = userName;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="AuthenticateUserResponse", Namespace="http://tempuri.org/")]
public partial class AuthenticateUserResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public bool AuthenticateUserResult;
    
    public AuthenticateUserResponse()
    {
    }
    
    public AuthenticateUserResponse(bool AuthenticateUserResult)
    {
        this.AuthenticateUserResult = AuthenticateUserResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetStockItem", Namespace="http://tempuri.org/")]
public partial class GetStockItemRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string code;
    
    public GetStockItemRequest()
    {
    }
    
    public GetStockItemRequest(string code)
    {
        this.code = code;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetStockItemResponse", Namespace="http://tempuri.org/")]
public partial class GetStockItemResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public StockItem GetStockItemResult;
    
    public GetStockItemResponse()
    {
    }
    
    public GetStockItemResponse(StockItem GetStockItemResult)
    {
        this.GetStockItemResult = GetStockItemResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetCostPlaces", Namespace="http://tempuri.org/")]
public partial class GetCostPlacesRequest
{
    
    public GetCostPlacesRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetCostPlacesResponse", Namespace="http://tempuri.org/")]
public partial class GetCostPlacesResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/StockService")]
    public CostPlace[] GetCostPlacesResult;
    
    public GetCostPlacesResponse()
    {
    }
    
    public GetCostPlacesResponse(CostPlace[] GetCostPlacesResult)
    {
        this.GetCostPlacesResult = GetCostPlacesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="Book", Namespace="http://tempuri.org/")]
public partial class BookRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string itemNr;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public decimal quanity;
    
    public BookRequest()
    {
    }
    
    public BookRequest(string itemNr, decimal quanity)
    {
        this.itemNr = itemNr;
        this.quanity = quanity;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="BookResponse", Namespace="http://tempuri.org/")]
public partial class BookResponse
{
    
    public BookResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StockServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IStockService>, IStockService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://10.0.2.89:100/StockService.svc");
    
    public StockServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private GetDataResponse GetData(GetDataRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/GetData";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/GetDataResponse";
        info.ResponseIsWrapped = true;
        GetDataResponse retVal = base.Invoke<GetDataRequest, GetDataResponse>(info, request);
        return retVal;
    }
    
    public string GetData(int value)
    {
        GetDataRequest request = new GetDataRequest(value);
        GetDataResponse response = this.GetData(request);
        return response.GetDataResult;
    }
    
    private GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContractRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/GetDataUsingDataContract";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/GetDataUsingDataContractResponse";
        info.ResponseIsWrapped = true;
        GetDataUsingDataContractResponse retVal = base.Invoke<GetDataUsingDataContractRequest, GetDataUsingDataContractResponse>(info, request);
        return retVal;
    }
    
    public CompositeType GetDataUsingDataContract(CompositeType composite)
    {
        GetDataUsingDataContractRequest request = new GetDataUsingDataContractRequest(composite);
        GetDataUsingDataContractResponse response = this.GetDataUsingDataContract(request);
        return response.GetDataUsingDataContractResult;
    }
    
    private AuthenticateUserResponse AuthenticateUser(AuthenticateUserRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/AuthenticateUser";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/AuthenticateUserResponse";
        info.ResponseIsWrapped = true;
        AuthenticateUserResponse retVal = base.Invoke<AuthenticateUserRequest, AuthenticateUserResponse>(info, request);
        return retVal;
    }
    
    public bool AuthenticateUser(string userName, string password)
    {
        AuthenticateUserRequest request = new AuthenticateUserRequest(userName, password);
        AuthenticateUserResponse response = this.AuthenticateUser(request);
        return response.AuthenticateUserResult;
    }
    
    private GetStockItemResponse GetStockItem(GetStockItemRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/GetStockItem";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/GetStockItemResponse";
        info.ResponseIsWrapped = true;
        GetStockItemResponse retVal = base.Invoke<GetStockItemRequest, GetStockItemResponse>(info, request);
        return retVal;
    }
    
    public StockItem GetStockItem(string code)
    {
        GetStockItemRequest request = new GetStockItemRequest(code);
        GetStockItemResponse response = this.GetStockItem(request);
        return response.GetStockItemResult;
    }
    
    private GetCostPlacesResponse GetCostPlaces(GetCostPlacesRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/GetCostPlaces";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/GetCostPlacesResponse";
        info.ResponseIsWrapped = true;
        GetCostPlacesResponse retVal = base.Invoke<GetCostPlacesRequest, GetCostPlacesResponse>(info, request);
        return retVal;
    }
    
    public CostPlace[] GetCostPlaces()
    {
        GetCostPlacesRequest request = new GetCostPlacesRequest();
        GetCostPlacesResponse response = this.GetCostPlaces(request);
        return response.GetCostPlacesResult;
    }
    
    private BookResponse Book(BookRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IStockService/Book";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IStockService/BookResponse";
        info.ResponseIsWrapped = true;
        BookResponse retVal = base.Invoke<BookRequest, BookResponse>(info, request);
        return retVal;
    }
    
    public void Book(string itemNr, decimal quanity)
    {
        BookRequest request = new BookRequest(itemNr, quanity);
        BookResponse response = this.Book(request);
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IStockService/GetData", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetData", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetDataUsingDataContract", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetDataUsingDataContract", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IStockService/AuthenticateUser", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/AuthenticateUser", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetStockItem", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetStockItem", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetCostPlaces", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/GetCostPlaces", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IStockService/Book", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IStockService/Book", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IStockService/GetDataResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetDataResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetDataUsingDataContractResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetDataUsingDataContractResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IStockService/AuthenticateUserResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/AuthenticateUserResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetStockItemResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetStockItemResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetCostPlacesResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/GetCostPlacesResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IStockService/BookResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStockService/BookResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
